name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test iOS app
        run: |
          xcodebuild test \
            -scheme ChatWithAI \
            -destination 'platform=iOS Simulator,name=iPhone 16'\
            -only-testing:ChatWithAITests

